version: '2'
services:
    practise-app:
        image: practise
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=practise-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    practise-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: practise-cassandra
    practise-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=practise-cassandra
    practise-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: practise-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
